### ISSUE TITLE
.gitignore in htdocs

### ISSUE THREAD

**Issue by hhirsch** [AydinHassan/magento-core-composer-installer#15]
In the Magento root it adds .gitignore for the whole magento core. But I want to commit this as part of the deployment process so I need to check the core in.

Is there an option I can set?

**Comment by AydinHassan** [comment]
Hi @hhirsch. There is no way to do this currently. I wanted this tool to be a solution which completely utilises Composer. I don't really see the need for this feature when managing dependencies with Composer. I won't add this feature personally unless a lot of people request it. 

You can submit a PR yourself and I will review it, but if it adds a lot of code and isn't particularly simple, I can't guarantee i'll merge it.

I think it kind of defeats the point of using Composer if you are going to commit the core. 

I want this tool to be as simple as possible and perform 1 small task.

**Comment by hhirsch** [comment]
Ok. I can't make the deploy depend on whether github is up. So I think I have to look for another solution. Thanks anyhow. I am sure composer installer covers a lot of use cases.

**Comment by AydinHassan** [comment]
I understand, but this problem isn't specific to this project, you could argue that against the whole of the Composer eco-system and thesame as the majority of the Ruby and Node community. Tools like Capistrano pull the repository on deploy, what if GitHub is down then?

You may want to look in to [Toran Proxy](https://toranproxy.com/). This proxies all your dependencies on a server of your choice. Then as long as this server is available you can always deploy.
