### ISSUE TITLE
Why do we need extra.map?

### ISSUE THREAD

**Issue by razbakov** [AydinHassan/magento-core-composer-installer#17]
Is extra.map used?

you can test it:

1) create composer.json with this content:

```
{
    "repositories": {
        "magento": {"type":"git", "url":"https://github.com/firegento/magento"},
        "firegento": {
            "type": "composer",
            "url": "http://packages.firegento.com"
        }
    },
    "require": {
        "firegento/magento": "1.9.2.0"
    },
    "extra": {
        "magento-root-dir": "src",
        "auto-append-gitignore": true,
        "magento-deploystrategy": "copy",
        "magento-force": true
    }
}
```

2) create `src` folder
3) run `composer update`
4) find `src/composer.json` which is not in `extra.map`

So what does the installer do? Just copying magento folder?

**Comment by AydinHassan** [comment]
This tool, doesn't use mappings. It just copies based on excludes and updates gitignore file so the core is not racked in your project repository. This is all explained in the docs.

**Comment by AydinHassan** [comment]
For example, I recommend to use this core package, with a minimal `compsoer.json` file: https://github.com/AydinHassan/magento-community

**Comment by razbakov** [comment]
@AydinHassan ok, thanks, I will check it again then,

we are aiming to bring all security patches and new versions to Firegento Magento repo as fast as possible: https://github.com/firegento/magento

Don't you want to join?

**Comment by AydinHassan** [comment]
Hi @razbakov. I am already managing https://github.com/WeareJH/magento-ce && https://github.com/AydinHassan/magento-community. I don't really have time for another, thanks for the offer though :)

**Comment by razbakov** [comment]
@AydinHassan I also managing http://github.com/kirchbergerknorr/magento, but I want to switch all our projects to https://github.com/firegento/magento and promote it as the community-supported magento-repo. Why do we need thousands of magento repo and so much overhead? On each security-patch each of us doing the same things thousand of times. Don't we want to simplify it?

**Comment by AydinHassan** [comment]
@razbakov It's how we decide on install method where it get complicated though, some packages require mappings, some not, some require installer.

I'm away on holiday on Friday morning, so  will happily discuss it when I'm abck with, see if we can come up with something :)

**Comment by razbakov** [comment]
@AydinHassan have a good time! And when you get back check out my thoughts here http://razbakov.com/magento/2015/08/05/install-magento-via-composer.html

**Comment by AydinHassan** [comment]
I really would suggest updating the `magento-composer-installer` to `~3.0` we did a lot of work their stabilising it and cleaning it up.

**Comment by razbakov** [comment]
right! updated! thx!
