### ISSUE TITLE
No reaction on Redeploy 

### ISSUE THREAD

**Issue by luckyraul** [AydinHassan/magento-core-composer-installer#20]
No reaction to ```php composer.phar run-script post-install-cmd -- --redeploy```

One first deploy with shared vendor has magento core files. Others don't.

**Comment by AydinHassan** [comment]
There is no such `--redeploy` option here. Core is only installed when it is initially required or the version is updated. Please see the readme: https://github.com/AydinHassan/magento-core-composer-installer/blob/master/README.md

**Comment by luckyraul** [comment]
How I copy once again ? after installing ?

**Comment by AydinHassan** [comment]
I'm not sure, I don't really think a shard vendor is a great idea. If some update or install fails, your site is basically broken.

**Comment by luckyraul** [comment]
ok, thanks

**Comment by AydinHassan** [comment]
I would accept a PR to add such functionality but I'm a bit busy with other projects to do this myself now, sorry. Do you definitely need to share the vendor folder? How do you deploy?

**Comment by luckyraul** [comment]
You are right about shared vendor. 
btw I am deploying via mina and used shared vendor to speed up installations, but now I can't understand why I didn't noticed possible problems.

**Comment by AydinHassan** [comment]
@luckyraul I learn from experience also. We did it for the exact same reasons. Most of the time composer's cache should suffice. It usually makes a lot of difference!
