### ISSUE TITLE
composer require "magento/magento:1.9.2.2" does not work

### ISSUE THREAD

**Issue by craigcarnell** [AydinHassan/magento-core-composer-installer#24]
My Repo contains 1.9.2.2 and I've also tried your repo too.

I get:
```
composer require "magento/magento:1.9.2.2"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/magento could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

However running composer require "magento/magento:1.9.1.0" does work from your repo!

**Comment by AydinHassan** [comment]
Hey, could you show your `composer.json` file? And does your core repository have a `composer.json` file? Does it contain the correct name and is it tagged correctly?

Did you specify your core-repo as a repository in your projects composer.json file?

**Comment by craigcarnell** [comment]
my composer.json is:
```
{
    "require": {
        "aydin-hassan/magento-core-composer-installer": "~1.3"
    },
    "repositories": [
      {
        "type": "vcs",
        "url": "git@github.com:AydinHassan/magento-community.git"
      }
    ]
}
```

**Comment by AydinHassan** [comment]
I didn't tag 1.9.2.2 yet that's why. I'm not sure why your's doesn't work. You should check out the composer docs because this is unrelated to the installer. I'm travelling atm so not able to tag the new version, sorry.

**Comment by craigcarnell** [comment]
@AydinHassan How do you "tag" a release? I am on my own repo, It's created a 1.9 branch, The commit history says Magento Community 1.9.2.2 and my composer.json looks like this:

I did create as per your instructions

```
{
    "name": "magento/magento",
    "description": "Magento Community",
    "type": "magento-core"
}
```

**Comment by AydinHassan** [comment]
You need to use git, Composer uses git tags to pull in releases. You can do this on the command line or via GitHub by clicking on the releases tab.

**Comment by craigcarnell** [comment]
@AydinHassan Thanks works a treat :+1:

**Comment by AydinHassan** [comment]
Good to hear!

**Comment by craigcarnell** [comment]
@AydinHassan One final issue, my composer.json in the root was replaced with the one from my composer related repo?

**Comment by AydinHassan** [comment]
Ah, if you don't deploy to a subdirectory you will need to exclude that file from the copy, just do a search in the readme for excludes and you should see it

**Comment by craigcarnell** [comment]
@AydinHassan Exactly, thanks!
