### ISSUE TITLE
 [ErrorException] mkdir(): File exists - when running composer in Magento root directory

### ISSUE THREAD

**Issue by dlicheva** [AydinHassan/magento-core-composer-installer#25]
Hello Aydin,

I have encountered an issue with setting up the Magento root directory in composer.json.
The issue exists on Ubuntu 14.04 and is not a problem on an OS X EL Capitan 10.11.1

The issue appears with the following configuration:
composer.json in the mage-root directory:
{...
  "extra": {
    "magento-root-dir": "./"
}
Exception trace:
() at /home/workspace/mage-root/vendor/aydin-hassan/magento-core-composer-installer/src/CoreManager.php:236
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 mkdir() at /home/workspace/mage-root/vendor/aydin-hassan/magento-core-composer-installer/src/CoreManager.php:236
 AydinHassan\MagentoCoreComposerInstaller\CoreManager->ensureRootDirExists() at /home/workspace/mage-root/vendor/aydin-hassan/magento-core-composer-installer/src/CoreManager.php:176
 AydinHassan\MagentoCoreComposerInstaller\CoreManager->installCore() at n/a:n/a
 call_user_func() at phar://composer.phar/bin/../src/../src/Composer/EventDispatcher/EventDispatcher.php:152

mkdir() seems to throw an error when using a relative path for "magento-root-dir" .
I have managed to get it working using an absolute path:
{...
  "extra": {
    "magento-root-dir": "/home/workspace/mage-root/"
   }
}

However this makes this configuration usable only on a local copy.
Could you please help me use a relative path if it is possible?

Thanks,
Diana

**Comment by AydinHassan** [comment]
That is weird, I will try to take a look in the next couple of days

**Comment by AydinHassan** [comment]
Hey I just tried this out with a root dir of `./` on Ubuntu 14.04 and it worked fine for me. Seems I can't reproduce it :/

**Comment by AydinHassan** [comment]
Are you running `composer update` from the same folder or somewhere else? That is the only thing that I can think of

**Comment by dlicheva** [comment]
Yes, it's from the same folder.

**Comment by AydinHassan** [comment]
I don't really know then, it works for me. Try running composer with -vvv. The error is saying that your root directory does not exist and then it tries to create it and fails. Does the root directory have the correct permissions?

**Comment by dlicheva** [comment]
You are right, it was a file permissions issue! Works now. Thank you very much!

**Comment by AydinHassan** [comment]
Perfect, good to hear :)
