### ISSUE TITLE
Magento 2 CE and EE

### ISSUE THREAD

**Issue by craigcarnell** [AydinHassan/magento-core-composer-installer#28]
Hi,

Could you this be adapted/used to create your own composer repo of Magento 2?

**Comment by AydinHassan** [comment]
Magento 2 uses Composer out of the box, why would you need this?

**Comment by craigcarnell** [comment]
@AydinHassan To create your own core package. Mainly useful for enterprise edition, which is not a public repo.

**Comment by AydinHassan** [comment]
Sorry, I don't follow. You will have to be more specific. Why would EE be public? And if you have access to EE, surely yo have access to the repo?

**Comment by craigcarnell** [comment]
@AydinHassan EE is private like you say. And I would like to create a private repo of EE 2 and then in my other repos pull down from that using composer

**Comment by AydinHassan** [comment]
You still wouldn't need this tool. All this tool does is c+p everything from the vendor package to the doc root. Magento 2 works directly from the vendor directory.
