### ISSUE TITLE
Deploy Strategy error

### ISSUE THREAD

**Issue by boruchy** [AydinHassan/magento-core-composer-installer#29]
It seems that if using composer with "magento-deploystrategy" as symlink, the lib/Varian library ( a core lib) does net get deployed properly.

**Comment by AydinHassan** [comment]
`magento-deploystrategy` has nothing to do with this library.

Can you elaborate more on your issue please.

It would be helpful to provide your `composer.json` file as there must be something specific to your project not functioning correctly, thanks

**Comment by boruchy** [comment]
@AydinHassan 

{
  "require": {
    "magento/core": "1.9.2.1",
    "magento-hackathon/magento-composer-installer": "3.0.6",
    "aydin-hassan/magento-core-composer-installer": "1.3.0"
},
 "minimum-stability":"dev",
  "repositories": [
    {
      "type": "composer",
      "url": "http://packages.firegento.com"
    }
  ],
  "extra": {
    "magento-root-dir": "./src",
    "magento-deploystrategy": "symlink",
    "magento-force": true,
    "magento-core-deploy": {
      "excludes": [
        ".htaccess",
        "app/code/local.xml",
        "errors/local.xml",
        "composer.json"
      ],
      "git-ignore-append": true
    }
  }
}

**Comment by AydinHassan** [comment]
I just ran `composer update` in a clean directory using exactly that `composer.json` and `src/lib/Varien/` is present as expected.
