### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by craigcarnell** [AydinHassan/magento-core-composer-installer#31]
I am using Jenkins to deploy, the first time app/code/core is fetched from my magento repo, but the second time it's always empty.

Any ideas?

**Comment by AydinHassan** [comment]
Only the first time magento is installed via composer is it copied to the root dir. It doesn't copy if nothing is updated

**Comment by craigcarnell** [comment]
@AydinHassan Any way to override this behaviour?

**Comment by djallits** [comment]
I believe that is the preferred behavior, to leave the root directory intact after the initial installation, unless there was a bump in magento/magento versions. Otherwise, I could see this being a nightmare in production.

**Comment by AydinHassan** [comment]
Yeah sorry @craigcarnell there is no way to do that. As @djallits notes this is by design. You could just rm your vendor directory and run composer install again.

**Comment by craigcarnell** [comment]
@AydinHassan OK Will do that, acceptable solution! thanks
