### ISSUE TITLE
Require different Magento versions?

### ISSUE THREAD

**Issue by craigcarnell** [AydinHassan/magento-core-composer-installer#35]
I have a repo. One that requires EE and so it in it's composer.json it adds the magentoee github repo.

Depending on the situation, some times I will require CE instead (depending on the database that vhost points to).

Is there anyway to handle this? I can maintain 2 different branches, but I was wondering if there was another way

**Comment by AydinHassan** [comment]
Not really, not without changing `composer.json`. Surely a project is either CE or EE?

**Comment by craigcarnell** [comment]
@AydinHassan I have an app that can run off both. It's a seperate application to the main website, it runs Magento and points at the database.
It works fine however the issue is that if I deploy the one to an EE that is fine, but If I deploy to a CE it will then run the EE module installers etc which is not a good thing

**Comment by AydinHassan** [comment]
@craigcarnell It's not a use case I'd want this plugin to support, it doesn't sound very common. Maybe you can just use a script to replace the package name in `composer.json` or something.
