### ISSUE TITLE
.gitignore not updating

### ISSUE THREAD

**Issue by AndersMadsen** [AydinHassan/magento-core-composer-installer#36]
I've tried a few commands and putting them in the extra section of my composer.json

Updating the directory does not update the .gitignore.

**Comment by AydinHassan** [comment]
Can you show how you are running and your `composer.json` contents please?

Also note that the `.gitignore` file which is modified is the one within `magento-root-dir` _NOT_ the one in your project root.

**Comment by AndersMadsen** [comment]
I have my composer in the projects root, so the magento-root-dir is the same as that one, I cd to the project dir and run an update on composer

I have tried multiple variations of the gitignore options, but the .gitignore is always empty when doing so

Only when installing everything from scratch will the .gitignore be put into the project dir, but have the 10k lines.
`{
   
	"repositories": {
        "installer-magento-core": {
          "type": "git",
          "url": "https://github.com/AydinHassan/magento-core-composer-installer"
        },
        "magento": {
          "type":"git",
          "url":"https://github.com/firegento/magento"
        },
        "firegento": {
          "type": "composer",
          "url": "http://packages.firegento.com"
        }
    },
    "require": {
      "magento-hackathon/magento-composer-installer": "~3.0",
      "aydin-hassan/magento-core-composer-installer": "~1.2",
      "firegento/magento": "~1.9.2"
    },
	"config" : {
	  "secure-http":false,
	  "process-timeout": 2000
	},
    "extra": {
	  "magento-root-dir": "./",
      "magento-deploystrategy": "copy",
	  "auto-append-gitignore": false,
      "magento-force": true,
	  "magento-core-deploy" : {
            "excludes": [ 
                "composer.json"
            ],
			"git-ignore-append": false
         }
    }
	
}`

**Comment by AydinHassan** [comment]
@AndersMadsen The gitignore is only generated on an initial install of Magento or when magento is updated. Not on every `composer update`. The gitignore will be as long as there are files in Magento.

I just used the `composer.json` you posted and ran `composer install` the gitignore was correctly generated. I ran `composer update` and it was still there.

This seems correct to me?

**Comment by AndersMadsen** [comment]
I tried deploying magento with an exclude on .gitignore, didn't work on install, I didn't want the huge ignore file, but I have settled for something I did on my own.
