### ISSUE TITLE
[Feature Request] Use Hardlinks instead of copy

### ISSUE THREAD

**Issue by possi** [AydinHassan/magento-core-composer-installer#37]
Mage Core source is about 162M. As every file is copyed to htdocs, the project starts at 320M.
Using hardlinks should reduce the disk usage. Also it may increase the perforemance of installing the magento core.

**Comment by AydinHassan** [comment]
Hi, there are a few files in the core that don't work as links, that was my first approach. Feel free to investigate - but as I remember it wasn't possible to do with patching hackery. That's not something I want to do here.

Sent from my iPhone

On 17 Jun 2016, at 17:13, Jascha <notifications@github.com<mailto:notifications@github.com>> wrote:


Mage Core source is about 162M. As every file is copyed to htdocs, the project starts at 320M.
Using hardlinks should reduce the disk usage. Also it may increase the perforemance of installing the magento core.

-

**Comment by possi** [comment]
Did you try hardlinks or just symlink? Have you any idea where problems occur?
I'll give it a try.
