### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by infabo** [AydinHassan/magento-core-composer-installer#40]
I experienced the following behaviour, can't provide the exact console output but as I remember from my mind:

If you do a composer update and the magento-core package is going to be updated, the magento-core-composer-installer 

- first undeploys/deletes all core-files from the magento-docroot
- composer fetches the new package version (**which can last for several minutes on slow connections**) and afterwards
- the composer-installer redeploys the updated magento-core.

Even if the updated package is already in the composer-cache, this still leaves magento in a void-state for ~30 seconds.
This is a nightmare on production-environments because in the meantime between undeploy and redeploy the magento-installation is left in an "empty" state.

How to work around this issue?

**Comment by AydinHassan** [comment]
Hi, you should use a different deploy strategy - you really should not be doing a composer install on a live environment or at least on the publicly accessible code. Look in to using Capistrano or something similar, or even running the install locally, building a package and deploying that.

Even without this package, you will experience the same problem with just composer, there will be a small gap where it is removing, extracting and writing files after updates.

**Comment by infabo** [comment]
Good point. Unfortunately not economical for smaller projects to setup capistrano deployments. Seems like to live with this restriction and place a index.html to show a maintenance page.

**Comment by AydinHassan** [comment]
If you invest a little time with Capistrano it will make your life a lot simpler. We have a sort of skeleton project that we start all projects from with the Capistrano config already in there, also including base Composer config. Then when we initialise a project all we have to do is change the server address.

Capistrano is still manual also, so you don't have to pay for anything. Just run `cap production deploy`

Anyway i'll close this now as it's not something I want to solve with this tool.
