### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by luckyraul** [AydinHassan/magento-core-composer-installer#43]
Deprecation Notice: The callback AydinHassan\MagentoCoreComposerInstaller\CoreManager::installCore declared at /vendor/aydin-hassan/magento-core-composer-installer/src/CoreManager.php accepts a Composer\Script\PackageEvent but post-package-install events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:317

**Comment by AydinHassan** [comment]
Already fixed in 1.4 😀

**Comment by luckyraul** [comment]
no, still same problem

**Comment by AydinHassan** [comment]
Maybe you can send a PR then because the code looks right to me?

Sent from my iPhone

On 26 Dec 2016, at 12:30, Nikita <notifications@github.com<mailto:notifications@github.com>> wrote:


no, still same problem

-
