### ISSUE TITLE
Behavior of the "git-ignore-append" configuration

### ISSUE THREAD

**Issue by ajardin** [AydinHassan/magento-core-composer-installer#44]
Hello,

Thanks for your plugin, it works almost exactly how I expected. :-)
The only issue I have is related to fact that the .gitignore file is updated when Magento files are copied into the project directory.

In our project, we defined a .gitignore file with Magento Core directories and some specific paths. This project uses the Magento structure without the core files. So we don't need to automatically update the file through Composer. And maybe I misunderstood something, but it seems for me that this use case is currently not possible. 
By the way, I don't know why but my updated .gitignore contains all files and not your list of ignored directories.

My suggestion would be to slighty change the "git-ignore-append" behavior: rather than copy each line into the .gitignore file and then clear the whole file, the addEntry() method could be inside a simple condition. If it makes sense for you, I can try to create a pull request with that change.

Regards.

**Comment by AydinHassan** [comment]
Hi @ajardin - sorry for not responding, I seem to not be getting notifications for this repo anymore :(.  I'm not sure I'm following what you describe, but there has been a recent PR to disable the gitignore so maybe that helps your issue?

It should be merged soon, see #45

**Comment by ajardin** [comment]
Hi @AydinHassan,

Haha don't worry, I had also a few troubles with GitHub notifications in the past.

You're right, this pull request would totally suits my need! I let you choose if you prefer to close this issue right now or once #45 will be merged.

Thanks again.

**Comment by AydinHassan** [comment]
@ajardin tagged 1.5.0 :)
