### ISSUE TITLE
Updating from 1.9.3.1 to 1.9.3.6 gives blanco page

### ISSUE THREAD

**Issue by jonasvanderhaegen** [AydinHassan/magento-core-composer-installer#46]
Hi Aydin

This is a real nice feature to have on shops. I'm trying to figure out why'd I get a blanco page when switching from 1 to 6. Have you encountered such problems like blanco pages when upgrading? 

What would you recommend doing if that happens, I'd guess clear cache or something but can't figure it out at the moment.

Thanks in advance.

Jonas

**Comment by AydinHassan** [comment]
Hi @jonasvanderhaegen - I'm sorry I can't really help you. I don't use Magento anymore! I would try and enable developer mode and maybe check the logs and report files if you haven't already though!

**Comment by Konafets** [comment]
Is this project abandon then?

**Comment by AydinHassan** [comment]
No - but this is not a problem with the installer -it’s a magento configuration or system problem.
