### ISSUE TITLE
Magento 1 Official PHP 7.2 Patch

### ISSUE THREAD

**Issue by dgitman** [AydinHassan/magento-core-composer-installer#48]
Is it possible to use magento-core-composer-installer and the Magento 1 official PHP 7.2 patch? [https://community.magento.com/t5/News-Announcements/PHP-7-2-Support-Patches-for-Magento-1-are-now-available/m-p/106999](https://community.magento.com/t5/News-Announcements/PHP-7-2-Support-Patches-for-Magento-1-are-now-available/m-p/106999)

**Comment by AydinHassan** [comment]
It should work with any package with a composer type set correctly as in the read me. So aslong as you have a patched composer package, yes!
