### ISSUE TITLE
Install mage via cli

### ISSUE THREAD

**Issue by thetailor** [AydinHassan/magento-core-composer-installer#49]
I get an error when I try to install Magento via cli using install.php

composer.json
`
"require": {
    "magento-hackathon/magento-composer-installer": "~3.0",
    "aydin-hassan/magento-core-composer-installer": "*",
    "openmage/magento-lts": "1.9.4.x-dev"
},
`

error
`Fatal error: Uncaught Error: Call to a member function insert() on bool in <root>/htdocs/app/code/core/Mage/Core/Model/Resource/Resource.php:133`

any idea?

**Comment by thetailor** [comment]
After a brief analysis I noticed that two files are missing in <root>/app/etc/
- local.xml.additional
- local.xml.template
They aren't excluded in composer.json

Workaround: copy files from vendor/magento-repo

**Comment by AydinHassan** [comment]
Hey, I’m not currently able to look at this I’m living out of my tent/car for some months. If you want to send a PR I can take a look when I get decent internet at some point but not in a position to debug and write code atm, sorry!

Sent from my iPhone

On 6 Jun 2019, at 17:02, Simone Gualtieri <notifications@github.com<mailto:notifications@github.com>> wrote:


After a brief analysis I noticed that two files are missing in /app/etc/

  *   local.xml.additional
  *   local.xml.template
They aren't excluded in composer.json

Workaround: copy files from vendor/magento-repo
