### ISSUE TITLE
Info - Correct .htaccess for different root dir of Magento?

### ISSUE THREAD

**Issue by salesigniter** [AydinHassan/magento-core-composer-installer#62]
Hi,

This is not really an issue just wondering if you could add to your readme the .htaccess to get Magento 1.9 (or Open Mage) working in Apache on a web hosts that doesn't support changing the root dir in conf? I have tried the below and it works on the customer side but the admin side gives a "Front controller reached 100 router match iterations" error after login. I know I could just change "magento-root-dir" to "/" in the config but I prefer to keep it cleaner with an htdocs folder. This is what I've tried:

```
RewriteEngine on
RewriteCond %{HTTP_HOST} ^site.com$ [NC,OR]
RewriteCond %{HTTP_HOST} ^www.site.com$
RewriteCond %{REQUEST_URI} !htdocs/
RewriteRule (.*) /htdocs/$1 [L]
RewriteRule ^(.*)$ /htdocs/index.php?/$1 [L]
```

**Comment by AydinHassan** [comment]
Hi, I'm reluctant to add this as it's not really the concern of this package and the htaccess (if you are using Apache) will be different for many setups.
