### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by adam-paterson** [AydinHassan/magento-core-composer-installer#7]
`mage` in the .gitignore is stopping any modules that use mage in their directory path from being added to the repo.

**Comment by AydinHassan** [comment]
Oh that's a good one. Guess everything in the `.gitignore` should be prepended with `/`

**Comment by AydinHassan** [comment]
I'll have a look at fixing this, probably tomorrow night

**Comment by adam-paterson** [comment]
Yeah, same for any Model's that end with Index.php. I'll fix it today, need it for a project :)

**Comment by AydinHassan** [comment]
awesome, can you add a test for it also? :)

**Comment by adam-paterson** [comment]
Of course

**Comment by AydinHassan** [comment]
Fixed in 1bb0799607d94d355cb70f7594772206301bd043

**Comment by clockworkgeek** [comment]
This is a good bug fix.  I look forward to it being tagged so I don't have to specify `:dev-master`

**Comment by AydinHassan** [comment]
@clockworkgeek it is already tagged as 1.2.1 😀

**Comment by clockworkgeek** [comment]
I must be seeing another bug because with 1.2.1 some paths in .gitignore don't have the leading slash.  Perhaps because [e59fea860ba90754397565b4eac6dbf8099347c0] was committed afterwards.

**Comment by AydinHassan** [comment]
Ah yeah. I've tagged 1.2.2 just now 🐊
